name: Release full artists list

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build list
        run: ./merge-lists.sh > artists.csv
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artists.csv

permissions:
  contents: write
